### PR TITLE
Update draco3dgltf

### LINKED ISSUE #153: gltfjsx command error.
Hello, the following error occurs when I run the `npx gtlfjsx model.gltf` command in a shell env and I'm a little confused. if anyone could point out what I'm doing wrong that would be amazing.

(node:6616) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 Parse
TypeError: fetch failed
    at Object.processResponse (node:internal/deps/undici/undici:5555:34)
    at node:internal/deps/undici/undici:5877:42
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### PR DESCRIPTION
**Pull request by ggozad**
Update gltfjsx
Fixes #153

### CODE REVIEW

**Comment by QAJOSEP** [comment]
Thanks @ggozad it's works even with node 18 version, how did you solve it? 

image

**Comment by drcmda** [comment]
thanks! and sorry for the wait, i don't get github notifications, everything relevant gets drowned out by hundreds of repos i was auto subscribed to. :-S

**Comment by ggozad** [comment]
Haha no worries, I am in the same situation 😂

**Comment by burnham** [comment]
> thanks! and sorry for the wait, i don't get github notifications, everything relevant gets drowned out by hundreds of repos i was auto subscribed to. :-S

Tahnk you very much 💯

**Pull request merged**
