### PR TITLE
chore(deps): Update to Yarn v4, Node.js v18, and fix a broken dependency

### PR DESCRIPTION
**Pull request by donmccurdy**
Changes in preparation for the update to glTF Transform v4. glTF Transform v4 requires a newer version of Sharp for texture compression, which in turn uses WebAssembly to support Deno environments and has some important changes to its installation process:

https://sharp.pixelplumbing.com/install#cross-platform

In general things should 'just work' for most users, but support for npm <10, yarn <3, and node.js <18 has been dropped. I've omitted the update to glTF Transform from this PR, and included only the infrastructural changes.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Based on https://sharp.pixelplumbing.com/install it sounds like Yarn v1 is still supported, but on maintenance mode. So hopefully that part won't be an issue for users, but I think it's worth going ahead and updating the Yarn version used here.

**Comment by drcmda** [comment]
@donmccurdy  i updated all dependencies and published, im using the yarn 1 fallback atm. im kind of scared updating to a later yarn due to work projects. is there a way to fix the cli or let it use yarn-latest without forcing the project to use a specific tool?

**Comment by donmccurdy** [comment]
Sharp hasn't forced a specific tool here — it allows [anything except Yarn v1](https://sharp.pixelplumbing.com/install), or the mentioned workaround for Yarn v1. It'd also be OK to upgrade everything except Sharp, and pin that at v0.32 indefinitely. I've been gradually switching my own projects to Yarn v4, which has been fine as long as I use `nodeLinker: node-modules`.

**Comment by donmccurdy** [comment]
@drcmda OK, let's merge https://github.com/pmndrs/gltfjsx/pull/253 as a starting point then,  to un-break package.json. I'll look into whether we can upgrade to glTF Transform v4 here without upgrading from Yarn v1.

**Comment by donmccurdy** [comment]
I see you merged https://github.com/pmndrs/gltfjsx/commit/21033c664c8aef7347da863a8bdf83bbc8e4adf7 already, thanks! Closing this PR.

**Pull request closed without merging**
